### ISSUE TITLE
Clear out legacy Gate Mode code - not currently supported

### ISSUE THREAD

**Issue by edkangdev** [JaneliaAPIG/spoke#30]

**Comment by JaneliaAPIG** [comment]
This feature was to (more) selectively display detected spikes only when a gate signal is active. It has not been tested since Spoke work resumed in 2015. 

No user is actively requesting this for now, so it is best to clear it out from the main code to simplify algorithm readability. A  branch to archive the original implementation was created at feature_restoreGateMode. 

A first attempt to clear out Gate code was made at commit 29a5cf4. However in testing this caused queue back-up to occur, for reasons not understood. So this was reverted for now at ab27067

**Comment by vijayiyer05** [comment]
77329f353faf90f933e0a0286b3302b1ea9283e3
